version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testpackage
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - cyclop
    - depguard
    - funlen
    - gochecknoglobals
    - gocognit
    - lll
    - mnd
    - nestif
    - nlreturn
    - paralleltest
    - tparallel
    - wrapcheck
    - wsl
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
        - pattern: ^ioutil\..*$
        - pattern: ^os\.(DirEntry|FileInfo|FileMode|Is.*|Mode.*)$
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
      - linters:
          - forbidigo
        path: ^cmd/xctrack/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/twpayne/go-xctrack
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
