name: Test
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: oldstable
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...